// Subtitle cues for William's narration clips: [seconds into the clip, text].
export const CUES = {
  '00-intro': [
    [0.2, 'Hey guys, my name is William.'],
    [5.2, "Today I'm going to read you a story — but more like show you an animation."],
    [13.0, 'Well… I have nothing to say. So, enjoy.'],
  ],
  '01-scene-1': [
    [0.5, 'Two kingdoms, one sky.'],
    [3.9, 'The Lettuce Kingdom strikes first.'],
    [7.4, 'So the Tomato Kingdom sends up its best supersonic jet.'],
    [17.4, 'The Lettuce Kingdom answers with a helicopter, high above everything.'],
    [24.8, 'A Tomato drone carries a sniper up and lets him go.'],
    [32.5, "There he puts a hole straight through an enemy paratrooper's chute."],
    [41.7, 'That soldier is not landing.'],
    [46.8, "Below them, a Lettuce soldier swings on a rope tied to the helicopter's tail,"],
    [58.3, 'trading fire with the machine gun on the Tomato roof.'],
    [64.6, 'And on the ground, one man keeps shooting at the enemy wall.'],
    [72.1, 'Tom!'],
  ],
  '02-scene-2': [
    [0.9, 'First missile. The Tomato silo fires.'],
    [7.9, 'The missile flies the whole way across the field and knocks the Lettuce base over.'],
    [16.6, 'In the same moment, the supersonic jet lets go of its own missile — watch it fly down the line and hit the helicopter.'],
    [31.5, 'The Lettuce Kingdom still has one card left.'],
    [35.9, 'Their drone drops a soldier straight at the Tomato roof to break the machine gun. And Tom has not moved.'],
    [49.2, 'He is still shooting at the wall.'],
  ],
  '03-scene-3': [
    [0.5, 'The Counterstrike.'],
    [3.1, 'Now the Lettuce silo fires.'],
    [6.2, 'Their missile comes screaming back the other way and lands right on the Tomato roof.'],
    [16.9, 'The machine gun and every weapon up there are smashed to pieces.'],
    [23.3, 'The Tomato Kingdom does not stop.'],
    [27.0, 'Paratroopers drop onto the enemy roof to take out the laser guns that are still firing.'],
    [36.4, 'One of them is already dead metal.'],
    [42.4, 'And on the ground, Tom keeps doing the exact same thing: shooting at the base. Not at people. Just the base.'],
  ],
  '04-scene-4': [
    [0.5, 'The Tomato Bomb!'],
    [3.6, 'The Lettuce base is wrecked.'],
    [7.1, 'And then the ground opens, and a whole new set of high-tech weapons rises out of it — including a second rocket launcher.'],
    [22.4, 'A Tomato jet fires, and the missile goes straight into the new machines.'],
    [30.3, 'Then someone is hanging upside down at the edge of the picture, roped by the ankles… and it is Tom.'],
    [45.0, 'He was a Lettuce Kingdom spy the whole time. Years of it.'],
    [51.5, 'That is why he only ever shot at walls.'],
    [58.6, 'He was faking every attack. A spy in the family — and a nuclear weapon buried next door.'],
    [70.3, 'The King has heard enough.'],
    [75.3, "He sends up the Tomato Kingdom's strongest weapon."],
    [80.8, 'The Tomato Bomb comes down between the two kingdoms and goes off like a small sun — and Tom hangs there and shakes.'],
  ],
  '05-interlude': [
    [1.1, "Tom's Choice."],
    [3.5, 'Hanging there upside down, Tom starts remembering.'],
    [7.9, 'He came to the Tomato Kingdom when he was very small.'],
    [13.7, 'He met his best friends here. He got married here. He has kids.'],
    [25.6, 'His kids have never actually lived anywhere else.'],
    [31.0, 'He was born in the Lettuce Kingdom — but this is the place he actually loves.'],
    [40.7, 'And he knows something nobody else does.'],
    [45.3, 'The nuclear weapon under the Lettuce base is already armed.'],
    [51.5, 'In two days it goes off, and his home — and the whole Tomato Kingdom — will go with it.'],
    [59.5, 'He is done watching his friends die for the wrong side of the story.'],
    [66.5, 'So Tom switches sides for real, and offers to lead the way in.'],
  ],
  '06-scene-5': [
    [0.5, 'Shut it down!'],
    [3.6, 'Tom teams up with Ryley,'],
    [7.1, 'the best SWAT operator the Tomato Kingdom has — the one who made it home from planet 4546B'],
    [21.5, 'and knows how to move in a radiation suit.'],
    [29.9, 'Both of them suit up.'],
    [32.7, 'One knows the enemy. The other knows how to survive down there.'],
    [43.8, 'They rope down the launch silo together.'],
    [52.4, 'What they find on level B1 is strange.'],
    [56.7, 'The guards left behind have all gone wrong from the radiation.'],
    [64.0, 'One is walking upside down on the ceiling.'],
    [66.8, 'One is floating in the air with his arms out.'],
    [76.1, 'And one locked himself in the shielded safe room — no suit, no way out — so he just sits there playing video games forever.'],
    [90.0, 'None of them are holding a weapon anymore.'],
    [95.5, 'One guard is still together enough to try to stop them. He does not stop them for long.'],
    [106.0, 'Down on B2 they find the launcher.'],
    [110.5, 'They do not have the password, so they do it the rough way —'],
    [118.1, 'and the whole reactor circuit blows out and catches fire.'],
    [123.0, 'Good thing there is a CO₂ bottle on the wall.'],
    [127.5, 'They put the fire out —'],
    [130.4, 'then point the same bottle at the floor, turn it into a jet,'],
    [138.2, 'and ride it up the air duct back to the surface.'],
  ],
  '07-ending': [
    [0.4, 'Tomato Kingdom wins!'],
    [3.8, 'Dun, dun, dun…'],
    [13.6, 'Every Lettuce Kingdom base near the Tomato Kingdom is destroyed.'],
    [19.8, 'Their soldiers are gone.'],
    [21.8, 'The nuclear launcher is dead.'],
    [24.0, 'The fire is out, and two men rode a fire extinguisher home through an air duct.'],
    [31.2, 'One of them was supposed to be the enemy.'],
  ],
};
